### ISSUE TITLE
Oxygen Cloud

### ISSUE THREAD

**Issue by connor33341** [pikapower9080/pikapower9080.github.io#8]
# Oxygen Cloud 
It has been awhile since I have logged into Minecraft without a mod loader, I saw oxygen cloud was on my server list. But every connection failed. I am wondering what happened to the server, I see that the oxygen cloud page has been removed from the website. Is the server gone? Or did it just change addresses.
[Deletion Commit](https://github.com/pikapower9080/pikapower9080.github.io/commit/f121529f0bb89aeaa39c0a47e117d212e9b1ce1a)
[Old Files](https://github.com/pikapower9080/pikapower9080.github.io/tree/0b03d25cf2c7855b0de253f0c0bbbad084929a13/oxygencloud)
### connor_33341

>

**Comment by bleov** [comment]
It's been gone for a while since nobody played on it and I didn't feel like continuing to pay the bill, the map download is here: https://www.mediafire.com/file/7c4ek72b7rdic7u/oxygencloud.zip/file

![image](https://github.com/pikapower9080/pikapower9080.github.io/assets/48164825/d41b921d-36cf-477f-a161-fad91c7b8ddf)

**Comment by connor33341** [comment]
.
